//------------------------------------------------------------------------------
// <auto-generated>
//     Resource key constants for Lang.Avalonia.Json.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NexusDash;

public static class NexusDashL
{
    public const string AppName = "NexusDash.NexusDashL.AppName";
    public const string AppSubtitle = "NexusDash.NexusDashL.AppSubtitle";
    public const string ThemeMenu = "NexusDash.NexusDashL.ThemeMenu";
    public const string DarkTheme = "NexusDash.NexusDashL.DarkTheme";
    public const string LightTheme = "NexusDash.NexusDashL.LightTheme";
    public const string LanguageMenu = "NexusDash.NexusDashL.LanguageMenu";
    public const string SimplifiedChinese = "NexusDash.NexusDashL.SimplifiedChinese";
    public const string TraditionalChinese = "NexusDash.NexusDashL.TraditionalChinese";
    public const string English = "NexusDash.NexusDashL.English";
    public const string Japanese = "NexusDash.NexusDashL.Japanese";
    public const string SearchPlaceholder = "NexusDash.NexusDashL.SearchPlaceholder";
    public const string Pause = "NexusDash.NexusDashL.Pause";
    public const string Resume = "NexusDash.NexusDashL.Resume";
    public const string EndProcess = "NexusDash.NexusDashL.EndProcess";
    public const string EndProcessTree = "NexusDash.NexusDashL.EndProcessTree";
    public const string ProcessTree = "NexusDash.NexusDashL.ProcessTree";
    public const string Treemap = "NexusDash.NexusDashL.Treemap";
    public const string Details = "NexusDash.NexusDashL.Details";
    public const string Handles = "NexusDash.NexusDashL.Handles";
    public const string Network = "NexusDash.NexusDashL.Network";
    public const string Services = "NexusDash.NexusDashL.Services";
    public const string Startup = "NexusDash.NexusDashL.Startup";
    public const string Pid = "NexusDash.NexusDashL.Pid";
    public const string ParentPid = "NexusDash.NexusDashL.ParentPid";
    public const string ProcessName = "NexusDash.NexusDashL.ProcessName";
    public const string Cpu = "NexusDash.NexusDashL.Cpu";
    public const string Memory = "NexusDash.NexusDashL.Memory";
    public const string Disk = "NexusDash.NexusDashL.Disk";
    public const string NetworkColumn = "NexusDash.NexusDashL.NetworkColumn";
    public const string Gpu = "NexusDash.NexusDashL.Gpu";
    public const string Path = "NexusDash.NexusDashL.Path";
    public const string CommandLine = "NexusDash.NexusDashL.CommandLine";
    public const string StartTime = "NexusDash.NexusDashL.StartTime";
    public const string NoProcessSelected = "NexusDash.NexusDashL.NoProcessSelected";
    public const string HandlesSearchPlaceholder = "NexusDash.NexusDashL.HandlesSearchPlaceholder";
    public const string HandlesUnavailable = "NexusDash.NexusDashL.HandlesUnavailable";
    public const string NetworkUnavailable = "NexusDash.NexusDashL.NetworkUnavailable";
    public const string ServicesUnavailable = "NexusDash.NexusDashL.ServicesUnavailable";
    public const string StartupUnavailable = "NexusDash.NexusDashL.StartupUnavailable";
    public const string StatusRunning = "NexusDash.NexusDashL.StatusRunning";
    public const string StatusPaused = "NexusDash.NexusDashL.StatusPaused";
    public const string StatusSelected = "NexusDash.NexusDashL.StatusSelected";
    public const string StatusEnded = "NexusDash.NexusDashL.StatusEnded";
    public const string StatusEndFailed = "NexusDash.NexusDashL.StatusEndFailed";
    public const string StatusLanguageChanged = "NexusDash.NexusDashL.StatusLanguageChanged";
    public const string StatusThemeChanged = "NexusDash.NexusDashL.StatusThemeChanged";
    public const string MetricUnavailable = "NexusDash.NexusDashL.MetricUnavailable";
}
