<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <CentralPackageTransitivePinningEnabled>true</CentralPackageTransitivePinningEnabled>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="Avalonia" Version="12.1.0" />
    <PackageVersion Include="Avalonia.Desktop" Version="12.1.0" />
    <PackageVersion Include="Avalonia.Themes.Fluent" Version="12.1.0" />
    <PackageVersion Include="CodeWF.AvaloniaControls" Version="12.1.0.4" />
    <PackageVersion Include="CodeWF.AvaloniaControls.Themes" Version="12.1.0.4" />
    <PackageVersion Include="CodeWF.AvaloniaControls.ProDataGrid" Version="12.1.0.1" />
    <PackageVersion Include="CodeWF.AvaloniaControls.ProDataGrid.Themes" Version="12.1.0.1" />
    <PackageVersion Include="CodeWF.Log.Core" Version="12.1.0.23" />
    <PackageVersion Include="CodeWF.Markdown.Lite.Themes" Version="12.1.0.1" />
    <PackageVersion Include="CodeWF.EventBus" Version="3.4.5.11" />
    <PackageVersion Include="Irihi.Ursa.Themes.Semi" Version="2.1.0" />
    <PackageVersion Include="Lang.Avalonia.Json" Version="12.1.0.1" />
    <PackageVersion Include="Prism.Avalonia" Version="8.1.97.11073" />
    <PackageVersion Include="Prism.DryIoc.Avalonia" Version="8.1.97.11073" />
    <PackageVersion Include="ReactiveUI.Avalonia" Version="12.0.3" />
    <PackageVersion Include="Semi.Avalonia" Version="12.1.0" />
    <PackageVersion Include="System.Drawing.Common" Version="10.0.9" />
    <PackageVersion Include="System.Management" Version="10.0.9" />
    <PackageVersion Include="Tmds.DBus.Protocol" Version="0.94.2" />
    <PackageVersion Include="Xaml.Behaviors.Avalonia" Version="12.0.5" />
  </ItemGroup>
</Project>
