<Project>
  <PropertyGroup>
    <Version>0.1.3</Version>
    <Authors>沙漠尽头的狼</Authors>
    <Company>CodeWF</Company>
    <Product>NexusDash</Product>
    <Description>跨平台系统进程、网络通信和资源管理仪表盘。</Description>
    <PackageProjectUrl>https://codewf.com</PackageProjectUrl>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageTags>avalonia;atomui;process-manager;resource-monitor;tcp;udp;windows;linux;macos</PackageTags>
    <Copyright>Copyright (c) 2026 沙漠尽头的狼</Copyright>
    <NeutralLanguage>zh-CN</NeutralLanguage>
    <Deterministic>true</Deterministic>
  </PropertyGroup>
  <ItemGroup>
    <AssemblyAttribute Include="System.Reflection.AssemblyMetadataAttribute">
      <_Parameter1>Author</_Parameter1>
      <_Parameter2>$(Authors)</_Parameter2>
    </AssemblyAttribute>
    <AssemblyAttribute Include="System.Reflection.AssemblyMetadataAttribute">
      <_Parameter1>ProjectUrl</_Parameter1>
      <_Parameter2>$(PackageProjectUrl)</_Parameter2>
    </AssemblyAttribute>
    <AssemblyAttribute Include="System.Reflection.AssemblyMetadataAttribute">
      <_Parameter1>License</_Parameter1>
      <_Parameter2>$(PackageLicenseExpression)</_Parameter2>
    </AssemblyAttribute>
  </ItemGroup>
</Project>
