<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFrameworks>net11.0;net11.0-windows</TargetFrameworks>
    <Nullable>enable</Nullable>
    <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>Assets\logo.ico</ApplicationIcon>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
  </PropertyGroup>
  <ItemGroup>
    <AvaloniaResource Include="Assets\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AtomUI.Desktop.Controls" />
    <PackageReference Include="AtomUI.Desktop.Controls.DataGrid" />
    <PackageReference Include="Avalonia" />
    <PackageReference Include="Avalonia.Desktop" />
    <PackageReference Include="CodeWF.EventBus" />
    <PackageReference Include="CodeWF.Markdown.Lite.Themes" />
    <PackageReference Include="Lang.Avalonia.Json" />
    <PackageReference Include="Prism.DryIoc.Avalonia" />
    <PackageReference Include="ReactiveUI.Avalonia" />
    <PackageReference Include="System.Drawing.Common" Condition="'$(TargetFramework)' == 'net11.0-windows'" />
    <PackageReference Include="System.Management" Condition="'$(TargetFramework)' == 'net11.0-windows'" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\NexusDash.Controls\NexusDash.Controls.csproj" />
    <ProjectReference Include="..\NexusDash.Controls.Themes\NexusDash.Controls.Themes.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="..\..\CHANGELOG.zh-CN.md" Link="CHANGELOG.zh-CN.md" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
    <Content Include="..\..\CHANGELOG.md" Link="CHANGELOG.md" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
    <None Update="I18n\*.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <TargetPath>I18n\NexusDash\%(Filename)%(Extension)</TargetPath>
    </None>
  </ItemGroup>
</Project>
