<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFrameworks>net11.0;net11.0-windows</TargetFrameworks>
    <Nullable>enable</Nullable>
    <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>..\..\logo.ico</ApplicationIcon>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
  </PropertyGroup>
  <ItemGroup>
    <AvaloniaResource Include="Assets\**" />
    <AvaloniaResource Include="..\..\logo.ico" Link="Assets\logo.ico" />
    <AvaloniaResource Include="..\..\logo.png" Link="Assets\logo.png" />
    <AvaloniaResource Include="..\..\logo.svg" Link="Assets\logo.svg" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" />
    <PackageReference Include="Avalonia.Desktop" />
    <PackageReference Include="Avalonia.Themes.Fluent" />
    <PackageReference Include="CodeWF.AvaloniaControls" />
    <PackageReference Include="CodeWF.AvaloniaControls.Themes" />
    <PackageReference Include="CodeWF.AvaloniaControls.ProDataGrid" />
    <PackageReference Include="CodeWF.AvaloniaControls.ProDataGrid.Themes" />
    <PackageReference Include="CodeWF.EventBus" />
    <PackageReference Include="CodeWF.Log.Core" />
    <PackageReference Include="CodeWF.Markdown.Lite.Themes" />
    <PackageReference Include="Irihi.Ursa.Themes.Semi" />
    <PackageReference Include="Lang.Avalonia.Json" />
    <PackageReference Include="Prism.DryIoc.Avalonia" />
    <PackageReference Include="ReactiveUI.Avalonia" />
    <PackageReference Include="Semi.Avalonia" />
    <PackageReference Include="System.Drawing.Common" Condition="'$(TargetFramework)' == 'net11.0-windows'" />
    <PackageReference Include="System.Management" Condition="'$(TargetFramework)' == 'net11.0-windows'" />
    <PackageReference Include="Xaml.Behaviors.Avalonia" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\NexusDash.Controls\NexusDash.Controls.csproj" />
    <ProjectReference Include="..\NexusDash.Controls.Themes\NexusDash.Controls.Themes.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="..\..\UpdateLog.md" Link="UpdateLog.md" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
    <None Update="I18n\*.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <TargetPath>I18n\NexusDash\%(Filename)%(Extension)</TargetPath>
    </None>
  </ItemGroup>
</Project>
