<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net11.0</TargetFramework>
    <Nullable>enable</Nullable>
    <OutputType>Library</OutputType>
    <RootNamespace>NexusDash.Controls.Themes</RootNamespace>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\NexusDash.Controls\NexusDash.Controls.csproj" />
  </ItemGroup>
</Project>
